### ISSUE TITLE
creation of official IBC channels

### ISSUE THREAD

**Issue by nullmames** [CosmosContracts/mainnet#53]
Create channels IBC channels to Osmosis and Cosmoshub.

@faddat has been nominated by the Juno Core 2 team to create channels with the following numbers:

osmosis-1 -> channel-0
cosmoshub-4 -> channel-1

guides for relaying on official channels will be published in cosmoscontracts/docs and configuration files will ne stored in cosmoscontracts/relayer

**Comment by faddat** [comment]
Great. I don't also like to request that for now, others abstain from making channels.

It's a permissionless system so if for example you would like to have a contract on Juneau control staking on Akash, and you want to make a channel for that, God bless ya.

**Comment by nullmames** [comment]
so these channels are created. 
i think we should merge some configs into the repo.
propose to merge in the config for hermes from the juno docs to `http://gitbub.com/cosmoscontracts/mainnet/main/relayer/hermes`

**Comment by nullmames** [comment]
complete
